#!/bin/bash
#author scottcrossen

if ! git rev-parse --git-dir > /dev/null; then
  exit
fi

ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
UNADDED_FILES="$(git ls-files . --exclude-standard -odm --full-name)"
GIT_ROOT="$(git rev-parse --show-toplevel)"
if [[ "$(git rev-parse --abbrev-ref HEAD)" != "$USER"-dev ]]; then
  git branch -D "$USER"-dev || true
  git checkout -b "$USER"-dev
fi
git fetch
if [[ ! -z "$UNADDED_FILES" ]]; then
  git add .
  git commit -m "temp commit"
fi
/usr/bin/git push origin +"$USER"-dev
echo "Checking for git hooks"
if [[ -f "$GIT_ROOT"/.githooks ]]; then
  echo "Running webhooks"
  cat "$GIT_ROOT"/.githooks | while read LINE; do
    if [[ -f "$LINE" ]]; then
      echo "Running $LINE:"
      ./$LINE
      echo ""
    fi
  done
fi
if [[ ! -z "$UNADDED_FILES" ]]; then
  git reset --soft HEAD^
  git reset HEAD .
fi
git checkout "$ORIGINAL_BRANCH"
git status
