#!/bin/bash
#author scottcrossen

if ! /usr/bin/git rev-parse --git-dir > /dev/null; then
  exit
fi

PROTECTED_BRANCH='master'
if [ -d .git ]; then
  CURRENT_BRANCH=$(/usr/bin/git symbolic-ref HEAD | sed -e 's/refs\/heads\///g')
fi

if [ "$PROTECTED_BRANCH" == "$CURRENT_BRANCH" ] && [ "$1" == "commit" ]; then
    echo "You're about to commit while on local master. If this is really what you want then run:"
    printf "\n/usr/bin/git ${@:1}\n\n"
    exit 1
fi

if [ "$PROTECTED_BRANCH" == "$CURRENT_BRANCH" ] && [ "$1" == "push" ]; then
    echo "You're about to push while on local master. If this is really what you want then run:"
    printf "\n/usr/bin/git ${@:1}\n\n"
    exit 1
fi

if [ "$CURRENT_BRANCH" != "$PROTECTED_BRANCH" ] && [ "$1" == "push" ] && git diff "$CURRENT_BRANCH" "$PROTECTED_BRANCH" | grep -q "PRIVATE KEY"; then
    echo "You're about to push a diff with sensitive keywords. If this is really what you want then run:"
    printf "\n/usr/bin/git ${@:1}\n\n"
    exit 1
fi

/usr/bin/git "${@:1}"
EXIT_CODE=$?
if [ "$1" == "push" ]; then
  GIT_ROOT="$(git rev-parse --show-toplevel)"
  if [[ -f "$GIT_ROOT"/.webhooks ]]; then
    echo "Running webhooks"
    cat "$GIT_ROOT"/.githooks | while read LINE; do
      if [[ -f "$LINE" ]]; then
        echo "Running $LINE:"
        ./$LINE
        echo ""
      fi
    done
  fi
fi

exit "$EXIT_CODE"
