#!/bin/bash
#author scottcrossen

PROTECTED_BRANCH='master'
if [ -d .git ]; then
  CURRENT_BRANCH=$(/usr/bin/git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
fi

if [ "$PROTECTED_BRANCH" == "$CURRENT_BRANCH" ] && [ "$1" == "push" ]; then
    echo "You're about to push while on local master. If this is really what you want then run:"
    printf "\n/usr/bin/git ${@:1}\n\n"
    exit 1
fi

/usr/bin/git "${@:1}"
exit $?
