#!/bin/bash
#author scottcrossen

echo "Running script $(date)"

export DISPLAY=:0
BATTINFO=`acpi -b`
BATTPERCENTAGE="$(echo "$BATTINFO" | grep % | sed "s/^.*\s\([a-zA-Z]*\),\s\([0-9]*\)%.*$/\2% (\1)/g" | sort -nr | head -n 1)"

if echo "$BATTPERCENTAGE" | grep -q Discharging && [[ "$(echo "$BATTPERCENTAGE" | sed "s/^\([0-9]*\)%.*$/\1/g")" -lt 15 ]] ; then
    /usr/bin/notify-send "low battery" "$BATTPERCENTAGE"
    for PID in "$(pgrep gnome-session)"; do
	export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u "$LOGNAME")/bus"
        /usr/bin/notify-send "low battery" "$BATTPERCENTAGE"
    done
fi
