#!/bin/bash
#author scottcrossen

BATTINFO=`acpi -b`
BATTPERCENTAGE="$(echo "$BATTINFO" | grep % | sed "s/^.*\s\([a-zA-Z]*\),\s\([0-9]*\)%.*$/\2% (\1)/g" | sort -nr | head -n 1)"
if echo "$BATTPERCENTAGE" | grep -q Discharging && [[ "$(echo "$BATTPERCENTAGE" | sed "s/^\([0-9]*\)%.*$/\1/g")" -lt 15 ]] ; then
    DISPLAY=:0 /usr/bin/notify-send "low battery" "$BATTPERCENTAGE"
fi
