#!/bin/bash
#author scottcrossen

BATTINFO=`acpi -b`
if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 4 -d " " | sed s/%,//g` -lt 15 ]] ; then
    DISPLAY=:0 /usr/bin/notify-send "low battery" "$BATTINFO"
fi
